### PR TITLE
Fix distributed grid shell script

### PR DESCRIPTION
**Pull request by krmahadevan**

### CODE REVIEW

**Comment by krmahadevan** [comment]
@manoj9788 - Please take a look when you get a chance.

**Comment by manoj9788** [comment]
I believe the Pre-requisites need to be updated since Coursier is not needed now.

**Comment by krmahadevan** [comment]
@manoj9788 - coursier (or any other alternative to it) will always be needed because the tracing related jars are NOT available on the classpath by default.  We need to have them downloaded and made available in the classpath

**Comment by manoj9788** [comment]
Yes, I misread it, we've had a chat on it on Slack. pls ignore my comments here.

**Pull request merged**
